### PR TITLE
Fix calculation in:

### PR DESCRIPTION
**Pull request by akanshjain11**
1. Generating Checksum
 2. Calculating lmots.ls parameter.

### CODE REVIEW

**Comment by akanshjain11** [comment]
@AndiCover Please take a look.

**Comment by AndiCover** [comment]
@akjjj The keccakj library is missing. How did you solve that on your local environment?

**Comment by akanshjain11** [comment]
@AndiCover I did not require Shake256 digest for my use case, so I removed that dependency.

**Comment by AndiCover** [comment]
@akjjj Give me a few days. I will add the library to the project and run the tests again but I am busy at the moment.
How did you notice that the calculation is wrong?

**Comment by akanshjain11** [comment]
@AndiCover I was trying to verify a signature with this library and another python implementation. Found out that this library couldn't verify.

**Review by AndiCover — APPROVED** [review]

**Pull request merged**
